version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: coding-assistant-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: coding-assistant-api-gateway
    restart: always
    ports:
      - "${API_GATEWAY_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/coding_assistant?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your_secure_jwt_secret_key_here}
    depends_on:
      - mongodb
    networks:
      - app-network

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    container_name: coding-assistant-chat-service
    restart: always
    environment:
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/coding_assistant?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your_secure_jwt_secret_key_here}
      - MODEL_NAME=${MODEL_NAME:-TinyLlama/TinyLlama-1.1B-Chat-v1.0}
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: